### ISSUE TITLE
find public/opensource api for leetcode

### ISSUE THREAD

**Issue by Sifatul** [Sifatul/find-profile#2]

**Comment by nsourov** [comment]
We can get user data from leetcode using this grapqhl query. Note that, this will throw CORS error, maybe we need to update the `forward-api` to make `POST` request with body.
```js
const query = `
    query userProfile($username: String!) {
      matchedUser(username: $username) {
        profile {
          aboutMe
          company
          jobTitle
          school
        }
      }
    }
  `
const variables = { username: TARGET_USERNAME }

fetch("https://leetcode.com/graphql/", {method: 'POST', body: JSON.stringify({ query, variables })})
```

**Comment by Zishan3165** [comment]
I've noticed that the profile url for leetcode always has the following structure : 
https://leetcode.com/${username}/
We can just append the username from the search bar to the url and it should work provided the username is valid, if it is not valid then we won't show it. If we only have to show the url to the profile then I think we can save API calls with this approach.
What do you think? @nsourov @Sifatul

**Comment by Sifatul** [comment]
@nsourov implemented your api here 
https://github.com/Sifatul/find-profile/pull/8 
it does not give cors error but json parsing error. 
@Zishan3165 do take a look please

**Comment by Sifatul** [comment]
> I've noticed that the profile url for leetcode always has the following structure : [https://leetcode.com/${username}/](https://leetcode.com/$%7Busername%7D/) We can just append the username from the search bar to the url and it should work provided the username is valid, if it is not valid then we won't show it. If we only have to show the url to the profile then I think we can save API calls with this approach. What do you think? @nsourov @Sifatul

@Zishan3165 appending username at the end of leetcode domain will return nothing. its not an api.

**Comment by nsourov** [comment]
> @nsourov implemented your api here #8 it does not give cors error but json parsing error. @Zishan3165 do take a look please

Awesome, You used `forward-api` that's why no cors error

**Comment by Sifatul** [comment]
@nsourov can you take over from there?

**Comment by Sifatul** [comment]
@nsourov got data successfully in post man
<img width="771" alt="image" src="https://user-images.githubusercontent.com/10746740/181664753-ff64e60d-e8ea-4abd-880c-9d1adbe96b97.png">

**Comment by Sifatul** [comment]
@nsourov  got data from leetcode
<img width="1494" alt="image" src="https://user-images.githubusercontent.com/10746740/181669637-94495cd1-cf4f-46a6-aef3-5da13887090f.png">
