### ISSUE TITLE
improve UI to show user basic information

### ISSUE THREAD

**Issue by sifatul** [sifatul/find-profile#20]
basic information includes:
1. full name
2. email
3. country/nationality
4. gender
5. date of birth 
6. etc

**Comment by Sifatul** [comment]
basic information includes:
1. full name
2. email
3. country/nationality
4. gender
5. date of birth 
6. etc

**Comment by JRakin** [comment]
@Sifatul vaiya I'm picking this one

**Comment by Sifatul** [comment]
@JRakin thank you. I am adding you to the assignee.
