### ISSUE TITLE
form validation and api update for create account

### ISSUE THREAD

**Issue by sifatul** [sifatul/find-profile#33]
- use formik or reak-hook form to validate the form. 
- check links are valid and are of correct domain
- trim query params in links inserted in the form
- try to save as much clean data as possible
- on submit send the data to pages/api/user/createUserByEmail.ts 

f/e route: http://localhost:3000/account/create

**Comment by Sifatul** [comment]
@JRakin

**Comment by JRakin** [comment]
@Sifatul vaiya picking this one please assign me

**Comment by sifatul** [comment]
@JRakin you can use the the api at `pages/api/users/add.ts`
