### ISSUE TITLE
[f/e] show error message on inserting unwanted input

### ISSUE THREAD

**Issue by sifatul** [sifatul/find-profile#7]
currently platform supports only :

1.  valid url
2. valid username

if any user inputs a https url in a wrong format, i.e: `ww:://http://blah.com` or a name as `firstName SecondName` then it needs to show error message

**Comment by Mushfiqur06** [comment]
Brother, can I pick this?

**Comment by Sifatul** [comment]
@Mushfiqur06 definitely.

**Comment by sifatul** [comment]
Handled by @sifatul
